library(dplyr)
library(ggplot2)
source("visualization/utils.R")

static.heatmap <- function(date.sample = data$date %>% unique %>% .[1],
                           date.compare = data$date %>% unique %>% .[3],
                           class.sample = "Ground_vehicles",
                           fill = "rb_win_rate",
                           fill.limits = c(0, 100),
                           fill.log = FALSE,
                           colors = c(white, black, red, yellow, green, black, black),
                           colors.pos = c(0, 0.05, 0.4, 0.5, 0.6, 0.95, 1.0)) {
  # read the data generated by function cache_br_flat_df in stat_utils/concator.py
  data <- read.csv(cache.file.path)
  # filter the data
  data.sample <- data %>%
    filter(cls == class.sample) %>%
    mutate(rb_lower_br = rb_lower_br %>% as.factor)
  # select two date for compare
  data.now <- data.sample %>% filter(date == date.sample)
  data.before <- data.sample %>% filter(date == date.compare)

  # calculate trend
  data.trend <- data.now %>%
    select(nation, rb_lower_br, fill) %>%
    merge(data.before %>% select(nation, rb_lower_br, fill),
          by = c("nation", "rb_lower_br"), all.x = TRUE) %>%
    mutate(trend.up = .[, 3] > .[, 4]) %>%
    mutate(trend.down = .[, 3] < .[, 4]) %>%
    mutate(x = match(nation, nation_order), y = match(rb_lower_br, data.now$rb_lower_br %>% unique))

  data.trend.up <- data.trend %>% filter(trend.up) %>% select(x, y)
  data.trend.down <- data.trend %>%
    filter(trend.down) %>%
    select(x, y)

  if (fill.log)
    fill <- paste0("log10(", fill, ")")

  # plot
  data.now %>% ggplot +
    geom_tile(aes_string(x = "nation", y = "rb_lower_br", fill = fill), color = "black") +
    scale_fill_gradientn(colors = colors, values = colors.pos, limits = fill.limits) +
    scale_y_discrete(labels = data.now$rb_br) +
    scale_x_discrete(limits = nation_order) +
    ggtitle(paste("Heatmap of", fill, "for", class.sample, date.sample, sep = " ")) +
    labs(x = "Nation", y = "Battle Rating", caption = "Author: ControlNet, Source: Thunderskill") +
    annotate("point", x = data.trend.up$x, y = data.trend.up$y, shape = 24, fill = green, size = 1.5) +
    annotate("point", x = data.trend.down$x, y = data.trend.down$y, shape = 25, fill = red, size = 1.5)
}

static.heatmap.default.ground_vehicles.win_rate <- function() static.heatmap()

static.heatmap.default.ground_vehicles.battles <- function()
  static.heatmap(fill = "rb_battles_sum", fill.limits = c(2.5, 5.5), fill.log = TRUE,
                 class.sample = "Ground_vehicles", colors.pos = c(0, 0.01, 0.4, 0.5, 0.6, 0.99, 1.0))

static.heatmap.default.aviation.win_rate <- function()
  static.heatmap(class.sample = "Aviation", colors.pos = c(0, 0.01, 0.5, 0.6, 0.7, 0.99, 1.0))

static.heatmap.default.aviation.battles <- function()
  static.heatmap(fill = "rb_battles_sum", fill.limits = c(2.5, 5.5), fill.log = TRUE,
                 class.sample = "Aviation", colors.pos = c(0, 0.01, 0.4, 0.5, 0.6, 0.99, 1.0))

static.scatter <- function(date.sample, class.sample = "Ground_vehicles",
                           x = "rb_ground_frags_per_death", y = "rb_win_rate", size = "rb_battles",
                           x.limits = NULL, y.limits = NULL, colors = NULL, threshold = 0) {
  # read the ts data with specified date
  data <- paste0(joined.dir.path, "/", date.sample, ".csv") %>% read.csv
  # filter the class
  data.sample <- data %>% filter(cls == class.sample)
  # filter the vehicle with few battles
  data.sample <- data.sample[data.sample[size] > threshold,]

  # plot
  p <- data.sample %>% ggplot +
    geom_point(aes_string(x = x, y = y, color = "nation", size = size)) +
    scale_x_log10() +
    ggtitle(paste("The scatter of vehicles in", date.sample, sep = " ")) +
    labs(caption = "Author: ControlNet, Source: Thunderskill")
  if (!is.null(x.limits)) p <- p + xlim(x.limits)
  if (!is.null(y.limits)) p <- p + ylim(y.limits)
  if (!is.null(colors)) p <- p + scale_color_manual(values = colors)
  p
}

static.bars <- function(nation.sample,
                        date.sample = data$date %>% unique %>% .[1],
                        class.sample = c("Aviation", "Ground_vehicles"),
                        y = "rb_win_rate", y.limits = NULL) {
  # read data
  data <- read.csv(cache.file.path)
  data <- data %>%
    filter(date == date.sample) %>%
    filter(nation == nation.sample) %>%
    filter(cls %in% class.sample)

  # plot
  p <- data %>% ggplot +
    geom_bar(aes_string(x = "rb_br", y = y, fill = "cls"), stat = "identity", position = position_dodge()) +
    coord_flip(ylim = y.limits) +
    ggtitle(paste("Bar Chart for", paste(class.sample, collapse = " and "),
                  "of", nation.sample, date.sample, sep = " ")) +
    labs(caption = "Author: ControlNet, Source: Thunderskill")
  p
}

static.pie.battles <- function(date.sample,
                               class.sample = c("Aviation", "Ground_vehicles"),
                               mode = "rb",
                               colors = NULL) {
  # read joined data
  data <- paste0(joined.dir.path, "/", date.sample, ".csv") %>% read.csv
  data <- data %>%
    filter(cls %in% class.sample)

  battle.colname <- paste0(mode, "_battles")
  battle.sum.colname <- paste0(battle.colname, "_sum")
  # remove NA values
  data[is.na(data[battle.colname]),][battle.colname] <- 0
  # group and calculate the battles sum for each nation
  data.nation <- eval(parse(text = paste0("data %>%
    group_by(nation) %>%
    summarise(!!battle.sum.colname := sum(", battle.colname, "))")))

  # plot
  p <- data.nation %>% ggplot +
    geom_bar(aes_string(x = "\"\"", y = battle.sum.colname, fill = "nation"), stat = "identity") +
    coord_polar("y", start = 0) +
    labs(title = paste("Pie Chart for", toupper(mode), "Battles of", paste(class.sample, collapse = " and "),
                       "in", date.sample, sep = " "),
         caption = "Author: ControlNet, Source: Thunderskill",
         x = NULL,
         y = "Battles",
         fill = "Nation"
    ) +
    theme(axis.text.y = element_blank(), axis.line.y = element_blank(), axis.ticks.y = element_blank())

  if (!is.null(colors)) p <- p + scale_fill_manual(values = colors)
  p
}

staitc.pie.default.battles <- function() {
  data <- read.csv(cache.file.path)
  date.sample <- data$date %>% unique %>% .[1]
  static.pie.battles(date.sample, mode = "rb",
                     colors = c(red, blue, green, gray, purple, indigo, yellow, orange, brown))
}