library(dplyr)
library(data.table)
library(ggplot2)
library(gganimate)
require(gifski)
source("visualization/utils.R")

animation.render <- function(plot, width = 525, height = 600)
  animate(plot, renderer = gifski_renderer(), width = width, height = height)

animation.trend.heatmap <- function(class.sample = "Ground_vehicles", fill = "rb_win_rate",
                                    fill.limits = c(0, 100),
                                    colors = c(white, black, red, yellow, green, black, black),
                                    colors.pos = c(0, 0.05, 0.4, 0.5, 0.6, 0.95, 1.0)) {
  # read the data generated by function cache_br_flat_df in integration/concator.py
  data <- read.csv(cache.1.file.path) %>%
    as.data.table %>%
    mutate(date = date %>% as.Date.factor)
  # filter the data
  data.sample <- data %>%
    filter(cls == class.sample) %>%
    mutate(rb_lower_br = rb_lower_br %>% as.factor)
  # plot
  data.sample %>% ggplot +
    geom_tile(aes_string(x = "nation", y = "rb_lower_br", fill = fill), color = "black") +
    scale_y_discrete(labels = data.sample$rb_br) +
    scale_fill_gradientn(colors = colors, values = colors.pos, limits = fill.limits) +
    scale_x_discrete(limits = c("USA", "Germany", "USSR", "Britain", "Japan",
                                "France", "Italy", "China", "Sweden")) +
    ggtitle(paste("Heatmap of", fill, "for", class.sample, "{frame_time}", sep = " ")) +
    labs(x = "Nation", y = "Battle Rating", caption = "Author: ControlNet, Source: Thunderskill") +
    transition_time(date)
}

animation.trend.scatter <- function(class.sample = "Ground_vehicles",
                                    x = "rb_ground_frags_per_death", y = "rb_win_rate", size = "rb_battles",
                                    x.limits = NULL, y.limits = NULL, colors = NULL,
                                    x.log = FALSE, y.log = FALSE, size.log = FALSE, size.threshold = 0) {
  # TODO: size threshold not implemented yet
  # read all ts data
  file.paths <- paste0(joined.dir.path, "/", list.files(joined.dir.path))
  data <- file.paths %>%
    lapply(FUN = function(file) {
      data.sample <- read.csv(file) %>%
        filter(cls == class.sample) %>%
        select(x, y, nation, size) %>%
        mutate(date = file %>%
          as.Date(format = paste0(joined.dir.path, "/%Y-%m-%d.csv")))
      # filter the vehicle with few battles
      data.sample <- data.sample[data.sample[size] > size.threshold,]
      data.sample[complete.cases(data.sample),]
    }) %>%
    Reduce(f = rbind)

  # plot
  if (size.log) size <- paste0("log10(", size, ")")
  p <- data %>% ggplot +
    geom_point(aes_string(x = x, y = y, color = "nation", size = size)) +
    ggtitle(paste("Scatter for", class.sample, "{frame_time}", sep = " ")) +
    labs(caption = "Author: ControlNet, Source: Thunderskill")
  # modify some attributes
  if (x.log) p <- p + scale_x_log10()
  if (y.log) p <- p + scale_y_log10()
  if (!is.null(x.limits)) p <- p + xlim(x.limits)
  if (!is.null(y.limits)) p <- p + ylim(y.limits)
  if (!is.null(colors)) p <- p + scale_color_manual(values = colors)
  # add time axis
  p + transition_time(date)
}


animation.trend.bars <- function(nation.sample,
                                 class.sample = c("Aviation", "Ground_vehicles"),
                                 y = "rb_win_rate", y.limits = c(0, 100)) {
  # read data
  data <- read.csv(cache.1.file.path) %>%
    as.data.table %>%
    mutate(date = date %>% as.Date.factor)
  data <- data %>%
    filter(nation == nation.sample) %>%
    filter(cls %in% class.sample)

  # plot
  p <- ggplot(data) +
    geom_bar(aes_string(x = "rb_br", y = y, fill = "cls"), stat = "identity", position = position_dodge()) +
    coord_flip(ylim = y.limits) +
    ggtitle(paste("Bar Chart for", paste(class.sample, collapse = " and "),
                  "of", nation.sample, "{frame_time}", sep = " ")) +
    labs(caption = "Author: ControlNet, Source: Thunderskill")

  p + transition_time(date)
}
