library(dplyr)
library(data.table)
library(ggplot2)
source("visualization/utils.R")

trend.nations <- function(mode = "rb", class.sample = "Ground_vehicles",
                          y = "rb_win_rate", rb_br.sample = "9.7 ~ 10.7") {
  # read the data generated by function cache_br_flat_df in integration/concator.py
  data <- read.csv(cache.1.file.path(mode)) %>% as.data.table

  data.sample <- data %>%
    filter(rb_br == rb_br.sample) %>%
    filter(cls == class.sample) %>%
    mutate(date = date %>% as.Date.factor) %>%
    mutate(nation = nation %>% factor(
      levels = c("USA", "Germany", "USSR", "Britain", "Japan", "China", "Italy", "France", "Sweden"))
    )

  data.sample %>% ggplot +
    geom_line(aes_string(x = "date", y = y, color = "nation"), size = 1.2) +
    scale_x_date(date_labels = "%Y/%m") +
    labs(x = "Date", colors = "Nation", caption = "Author: ControlNet, Source: Thunderskill") +
    ggtitle(paste(y, "Trend for", class.sample, rb_br.sample, sep = " "))
}

trend.nations.battles <- function(mode="rb", class.sample = "Ground_vehicles", y = "rb_battles_sum") {
  # read the data generated by function cache_br_flat_df in integration/concator.py
  data <- read.csv(cache.all.file.path(mode)) %>% as.data.table

  data.sample <- data %>%
    filter(rb_br == "1.0 ~ 10.7") %>%
    filter(cls == class.sample) %>%
    mutate(date = date %>% as.Date.factor) %>%
    mutate(nation = nation %>% factor(
      levels = c("Germany", "USSR", "USA", "Sweden", "Britain", "Italy", "France", "Japan", "China"))
    )

  data.sample %>% ggplot +
    geom_area(aes_string(x = "date", y = y, fill = "nation"), color = "black") +
    scale_x_date(date_labels = "%Y/%m") +
    labs(x = "Date", fill = "Nation", caption = "Author: ControlNet, Source: Thunderskill") +
    scale_fill_manual(values = c(red, blue, green, gray, purple, indigo, yellow, orange, brown)) +
    ggtitle(paste("Battles Trend for", class.sample, sep = " "))
}

trend.vehicles <- function(vehicles, y = "rb_win_rate") {
  file.paths <- paste0(ts.dir.path, "/", list.files(ts.dir.path))
  data <- file.paths %>% lapply(FUN = function(file) {
    read.csv(file) %>%
      select(name, y) %>%
      filter(name %in% vehicles) %>%
      mutate(date = file %>% as.Date(format = paste0(ts.dir.path, "/ts%Y-%m-%d.csv")))
  }) %>% Reduce(f = rbind)

  data %>% ggplot +
    geom_line(aes_string(x = "date", y = y, color = "name")) +
    ggtitle("Trend of Vehicles") +
    scale_x_date(date_labels = "%Y/%m") +
    labs(x = "Date", color = "Vehicle", caption = "Author: ControlNet, Source: Thunderskill")
}
